### PR TITLE
Fixes backcompat issue with model.__repr__() in ST.

### LINKED ISSUE #2811: Style Transfer: model.__repr__() on model loaded from 5.8 throws error
Repro steps:

1. Load a model trained in Turi Create 5.8 into 6.0rc1.

2. Run `print(model)` in Python. 

Actual output:
```
KeyError: 'Field "_training_time_as_string" not in model. Available fields are batch_size, max_iterations, model, num_styles.'
```

Expected output:
No error.

### PR DESCRIPTION
**Pull request by shantanuchhabra**
Fixes #2811

### CODE REVIEW

File: src/toolkits/style_transfer/style_transfer.cpp [hunk 1]
```diff
@@ -484,8 +484,9 @@ gl_sarray style_transfer::convert_style_indices_to_filter(
 
 gl_sframe style_transfer::predict(variant_type data,
                                   std::map<std::string, flexible_type> opts) {
-  gl_sframe_writer result({"style_idx", "stylized_image"},
```
Comment (srikris) [inline src/toolkits/style_transfer/style_transfer.cpp]: Is this needed? Bad merge?

File: src/toolkits/style_transfer/style_transfer.cpp [hunk 2]
```diff
@@ -854,11 +855,21 @@ void style_transfer::import_from_custom_model(variant_map_type model_data,
...
+  const flex_int training_epochs = read_opts<flex_int>(model_data, "training_epochs");
+  const flex_int training_iterations = read_opts<flex_int>(model_data, "training_iterations");
+  const flex_int num_content_images = read_opts<flex_int>(model_data, "num_content_images");
+  const flex_float training_loss = read_opts<flex_float>(model_data, "training_loss");  
 
   add_or_update_state({{"model", model_type},
                        {"num_styles", num_styles},
                        {"max_iterations", max_iterations},
-                       {"batch_size", DEFAULT_BATCH_SIZE}});
+                       {"batch_size", DEFAULT_BATCH_SIZE},
```
Comment (srikris) [inline src/toolkits/style_transfer/style_transfer.cpp]: Won't this effect a unit test that check what things are in the state? If not, we don't have one so lets' add one

File: src/toolkits/style_transfer/style_transfer.cpp (hunk 1 above)
Comment (shantanuchhabra) [reply src/toolkits/style_transfer/style_transfer.cpp]: We are changing the output format of the SFrame, so this should be needed?

File: src/toolkits/style_transfer/style_transfer.cpp (hunk 2 above)
Comment (shantanuchhabra) [reply src/toolkits/style_transfer/style_transfer.cpp]: Does affect Python unit tests, looking into those right now.

File: src/toolkits/style_transfer/style_transfer.cpp (hunk 1 above)
Comment (shantanuchhabra) [reply src/toolkits/style_transfer/style_transfer.cpp]: My bad, sorry.

File: src/python/turicreate/test/test_style_transfer.py [hunk 3]
```diff
@@ -292,6 +292,17 @@ def test_save_and_load(self):
             self.test_get_styles_success()
             print("Get styles passed")
 
+    def test_state(self):
+        model = self.model
+        fields = model.__proxy__.list_fields()
+        assert "model" in fields
```
Comment (TobyRoseman) [inline src/python/turicreate/test/test_style_transfer.py]: In unit tests `self.assertTrue` is usually preferable to just `assert`. I believe using `assert` will cause failures to show up as errors which isn't ideal.

File: src/python/turicreate/test/test_style_transfer.py [hunk 4]
```diff
@@ -292,6 +292,17 @@ def test_save_and_load(self):
...
+        assert "num_styles" in fields
+        assert "_training_time_as_string" in fields
+        assert "training_epochs" in fields
+        assert "training_iterations" in fields
+        assert "num_content_images" in fields
+        assert "training_loss" in fields
```
Comment (TobyRoseman) [inline src/python/turicreate/test/test_style_transfer.py]: Are we expecting other keys might in `fields`? If not, it would be good to check there aren't any other thing in there.

File: src/python/turicreate/test/test_style_transfer.py (hunk 3 above)
Comment (shantanuchhabra) [reply src/python/turicreate/test/test_style_transfer.py]: Done, thanks!

File: src/python/turicreate/test/test_style_transfer.py (hunk 4 above)
Comment (shantanuchhabra) [reply src/python/turicreate/test/test_style_transfer.py]: We are expecting there to be other keys.
