### PR TITLE
mlmodel_image_feature_extractor should delete and replace cached models that cannot be loaded successfully

### LINKED ISSUE #1065: Image deep feature extractor vulnerable to invalid model cache
I finally reproduced the error we've been seeing in some CI tests:
```
RuntimeError: CoreML Error: Unable to extract model type from stream in compiled model: Error opening file stream: /var/folders/y5/9ghgwpqs77s9k8s7s881ng_m0000gn/T/model_cache/squeezenet_v1.1_modified.mlmodelc/coremldata.bin: unspecified iostream_category error
```
Inspection of this file reveals that it doesn't exist: there's an empty `squeezenet_v1.1_modified.mlmodelc` directory in the model cache. (Well, the directory contains some empty subdirectories.)

I don't know whether this invalid compiled model is the result of ordinary cleanup within a temp directory (returned by `NSTemporaryDirectory`) or something like a crash while writing the model in a previous run.

Regardless, we should make this code path robust to model cache corruption. For example, if the cached model cannot be loaded, follow the no-cache path (and regenerate the model).

### PR DESCRIPTION
**Pull request by nickjong**
Otherwise, a corrupted model cache will leave the machine in a state where feature extraction will repeatedly fail, across process launches, until the corrupted files are removed from the temporary directory

Fixes #1065

### CODE REVIEW

File: src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm [hunk 1]
```diff
@@ -162,10 +162,33 @@ void build_vision_feature_print_screen_spec(const std::string& model_path) {
...
   const std::string compiled_modified_model_path = download_path + "/" + model_name + "_modified.mlmodelc";
+  NSURL* compiledModelURL = [NSURL fileURLWithPath:[NSString stringWithUTF8String:compiled_modified_model_path.c_str()]];
+
+  // If the compiled modified model already exists on disk, attempt to load it.
+  if (boost::filesystem::exists(compiled_modified_model_path)) {
+
+    NSError* error = nil;
+    result = [MLModel modelWithContentsOfURL:compiledModelURL error:&error];
+
+    if (error) {
```
Comment (TobyRoseman) [inline src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm]: Do you want to check `result` here too?

Comment (nickjong) [reply src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm]: Good call! Once upon a time, Cocoa APIs had a standard behavior of returning nil for exactly one of the return value and the NSError out parameter, but I'm not sure this is really an invariant anymore. We may as well define success here as _both_ `error` being nil and `result` being non-nil.
