### PR TITLE
Fix "random_seed" state not found" bug for AC import for python model

### LINKED ISSUE #2378: AC import from custom model expects "random_seed" state not present in custom models
The initial implementation for importing an AC model saved with the old Python implementation attempts to read the "random_seed", but "random_seed" is only populated from C++.

https://github.com/apple/turicreate/blob/432af44763b18753e4524e9ba025e8915ac884eb/src/toolkits/activity_classification/activity_classifier.cpp#L523

### PR DESCRIPTION
**Pull request by jakesabathia2**
close #2378 
Fix the import function for python model.

### CODE REVIEW

File: src/ml/neural_net/weight_init.cpp [hunk 1]
```diff
@@ -40,28 +40,51 @@ xavier_weight_initializer::xavier_weight_initializer(
...
+    result.output_gate_recursion_fn = h2h_init_fn;
 
-  result.input_gate_bias_fn = zero_weight_initializer();
-  result.forget_gate_bias_fn = zero_weight_initializer();
-  result.block_input_bias_fn = zero_weight_initializer();
-  result.output_gate_bias_fn = zero_weight_initializer();
+    result.input_gate_bias_fn = zero_weight_initializer();
+    result.forget_gate_bias_fn = zero_weight_initializer();
+    result.block_input_bias_fn = zero_weight_initializer();
+    result.output_gate_bias_fn = zero_weight_initializer();
```
Comment (nickjong) [inline src/ml/neural_net/weight_init.cpp]: Why are we changing the indent level here? Didn't we already address this in the last PR?

File: src/toolkits/activity_classification/activity_classifier.cpp [hunk 2]
```diff
@@ -636,12 +639,19 @@ std::unique_ptr<data_iterator> activity_classifier::create_iterator(
   data_params.prediction_window = read_state<flex_int>("prediction_window");
   data_params.predictions_in_chunk = NUM_PREDICTIONS_PER_CHUNK;
   data_params.use_data_augmentation = use_data_augmentation;
-  data_params.random_seed = read_state<int>("random_seed");
+  if (!use_data_augmentation) {
```
Comment (nickjong) [inline src/toolkits/activity_classification/activity_classifier.cpp]: Nit: it would be more readable to switch the if and else cases and have the condition just be `if (use_data_augmentation)`

File: src/toolkits/activity_classification/activity_classifier.cpp [hunk 3]
```diff
@@ -636,12 +639,19 @@ std::unique_ptr<data_iterator> activity_classifier::create_iterator(
...
+    data_params.random_seed = 0;
+  } else {
+    data_params.random_seed = read_state<int>("random_seed");
+  }
   return std::unique_ptr<data_iterator>(new simple_data_iterator(data_params));
 }
 
 std::unique_ptr<compute_context> activity_classifier::create_compute_context()
     const {
+  if (state.find("use_tensorflow") == state.end()){
```
Comment (nickjong) [inline src/toolkits/activity_classification/activity_classifier.cpp]: I think we want to simplify this logic, not extend it. Again, please sync up with Shreya and Fareeha here

File: src/toolkits/activity_classification/activity_classifier.cpp [hunk 4]
```diff
@@ -680,47 +703,54 @@ std::unique_ptr<model_spec> activity_classifier::init_model() const
...
+      /* hidden_input */ "hiddenIn",
+      /* cell_input */ "cellIn",
+      /* hidden_output */ "hiddenOut",
+      /* cell_output */ "cellOut",
+      /* input_vector_size */ NUM_CONV_FILTERS,
+      /* output_vector_size */ LSTM_HIDDEN_SIZE,
       /* cell_clip_threshold */ LSTM_CELL_CLIP_THRESHOLD,
-      /* initializers */  lstm_weight_initializers::create_with_xavier_method(
-          NUM_CONV_FILTERS, LSTM_HIDDEN_SIZE, &random_engine));
+      /* initializers */ lstm_initializer);
```
Comment (nickjong) [inline src/toolkits/activity_classification/activity_classifier.cpp]: If running clang-format on this existing code, could we add spaces inside the comments so that the string constants continue to line up? The main goal here is to keep the code readable

Comment (jakesabathia2) [reply src/toolkits/activity_classification/activity_classifier.cpp]: hmmm it is not smart enough to do this.
Will add spaces by my self.
