### PR TITLE
[C++ OD] Add import function for Python saved model. Fix import function for C++ saved model.

### LINKED ISSUE #2399: OD Model crash when exporting cormel after import saved model.
When we import a saved model and export it to coreml,
we got errors.
```
model = tc.extensions.object_detector()
model.train(data,"annotations","image",tc.SFrame(),
	{'mlmodel_path':'./darknet.mlmodel','max_iterations':max_iterations})
tc._connect.main.get_unity().save_model(Wrapper(model), 'od_c++.model')
model = tc.extensions._wrap_function_return(tc._connect.main.get_unity().load_model('od_c++.model')['model'])
model.export_to_coreml('od_c++.mlmodel')
```
produce a crash:
```
Traceback (most recent call last):
  File "OD Test Cases.py", line 38, in <module>
    model.export_to_coreml('od_c++.mlmodel')
  File "/Users/henry/Desktop/turicreate/debug/src/python/turicreate/extensions.py", line 290, in <lambda>
    ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
  File "/Users/henry/Desktop/turicreate/debug/src/python/turicreate/extensions.py", line 277, in __run_class_function
    raise _ToolkitError(exc)
turicreate.toolkits._main.ToolkitError: Assertion failed: (/Users/henry/Desktop/turicreate/src/toolkits/coreml_export/neural_net_models_exporter.cpp:170): second_layer->input(0)=="image"  [leakyrelu-1_fwd == image]
. operator() from /Users/henry/Desktop/turicreate/src/toolkits/coreml_export/neural_net_models_exporter.cpp at 170
```

### PR DESCRIPTION
**Pull request by jakesabathia2**
In this PR I did several things:
1. Import for C++ saved model:
    Mainly in od_serialization.cpp::init_darknet_yolo(),
    I add max pooling layer, preprocessing layer, and change the input of the network,
    in order to make the nn_spec exactly the same as which we get when we train a model in c++.
    So in model_spec.cpp, I added pooling layer and preprocessing layer in order to use them. 
2. Import for Python saved model:
    Mainly in object_detector.cpp:import_from_custom(),
    It basically move the weight from saved Python model to c++.
3. Add "use_tensorflow" flag for Python model:
    Since currently when we evaluate a c++model, the code request a "use_tensorflow" flag,
    which wasn't presented in python model when it is trained with _advance_param =  
    {'use_tensorflow':false}. I simply add it to the model state.
    But for sure this flag should be removed in the future.

close #2399

### CODE REVIEW

File: src/ml/neural_net/model_spec.hpp [hunk 1]
```diff
@@ -147,6 +147,14 @@ class model_spec {
    */
   void add_sigmoid(const std::string& name, const std::string& input);
 
+  /**
+   * Appends a pooliong layer.
```
Comment (nickjong) [inline src/ml/neural_net/model_spec.hpp]: *pooling

File: src/ml/neural_net/model_spec.hpp [hunk 2]
```diff
@@ -324,8 +332,14 @@ class model_spec {
   // needed. If/when we support the full range of NeuralNetworkLayer values,
   // this could be shared in some form with coremltools.
 
-private:
+  /**
+   * Appends an preprocessing layer
```
Comment (nickjong) [inline src/ml/neural_net/model_spec.hpp]: *a preprocessing

File: src/ml/neural_net/model_spec.hpp [hunk 3]
```diff
@@ -324,8 +332,14 @@ class model_spec {
...
+   * Now only support image scaleing preprocessing though.
```
Comment (nickjong) [inline src/ml/neural_net/model_spec.hpp]: *scaling

File: src/python/turicreate/toolkits/object_detector/object_detector.py [hunk 4]
```diff
@@ -507,6 +507,7 @@ def update_progress(cur_loss, iteration):
         'training_iterations': training_iterations,
         'max_iterations': max_iterations,
         'training_loss': progress['smoothed_loss'],
+        'use_tensorflow': params['use_tensorflow']
```
Comment (nickjong) [inline src/python/turicreate/toolkits/object_detector/object_detector.py]: Please do not add this to the state here. We are getting rid of this codepath anyway

File: src/toolkits/object_detection/object_detector.cpp [hunk 5]
```diff
@@ -350,6 +350,74 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
   _load_version(iarc, version, *nn_spec_, state, anchor_boxes());
 }
 
+void object_detector::import_from_custom_model(variant_map_type model_data,
+                                               size_t version) {
+  auto it = model_data.find("_model");
+  flex_dict model = variant_get_value<flex_dict>(it->second);
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Since this value is quite large in memory, let's avoid copying it out. Instead, create a `const &` reference to it, import the model weights, and then delete it at the end

File: src/toolkits/object_detection/object_detector.cpp [hunk 6]
```diff
@@ -350,6 +350,74 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
...
+  model_data.erase(it);
+  auto it2 = model_data.find("_grid_shape");
+  std::vector<size_t> shape =
+      variant_get_value<std::vector<size_t>>(it2->second);
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Just in case, let's make this robust to `_grid_shape` not being present in the dictionary

File: src/toolkits/object_detection/object_detector.cpp [hunk 7]
```diff
@@ -350,6 +350,74 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
...
+  size_t height = shape[0];
+  size_t width = shape[1];
+  model_data.erase(it2);
+  model_data.insert(std::pair<std::string, size_t>("grid_height", height));
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Please prefer the more readable:
```
model_data.emplace("grid_height", height);
```

File: src/toolkits/object_detection/object_detector.cpp [hunk 8]
```diff
@@ -350,6 +350,74 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
...
+    flex_nd_vec mxnet_data_nd = mxnet_data_dict[i].second.to<flex_nd_vec>();
+    flex_nd_vec mxnet_shape_nd = mxnet_shape_dict[i].second.to<flex_nd_vec>();
+    const std::vector<double>& model_weight = mxnet_data_nd.elements();
+    const std::vector<double>& model_shape = mxnet_shape_nd.elements();
+    std::vector<float> layer_weight(model_weight.begin(), model_weight.end());
+    std::vector<size_t> layer_shape(model_shape.begin(), model_shape.end());
+    size_t index = layer_name.find('_');
+    layer_name =
+        layer_name.substr(0, index) + "_fwd_" + layer_name.substr(index + 1);
+    std::cout << layer_name << '\n';
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Please remove debugging code before pushing commits for review

File: src/toolkits/object_detection/object_detector.cpp [hunk 9]
```diff
@@ -528,7 +596,7 @@ void object_detector::perform_predict(gl_sframe data,
       /* w_out   */ grid_width,
       /* config  */ pred_config,
       /* weights */ get_model_params());
-
+
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Please don't introduce trailing whitespace

File: src/python/turicreate/toolkits/object_detector/object_detector.py [hunk 10]
```diff
@@ -506,7 +506,7 @@ def update_progress(cur_loss, iteration):
         'training_epochs': training_iterations * batch_size // num_images,
         'training_iterations': training_iterations,
         'max_iterations': max_iterations,
-        'training_loss': progress['smoothed_loss'],
+        'training_loss': progress['smoothed_loss']
```
Comment (nickjong) [inline src/python/turicreate/toolkits/object_detector/object_detector.py]: Nit: let's avoid mutating this line in this PR unnecessarily. Before, there was a trailing comma here.

(This way, we keep the `git blame` history for this line simpler.)

File: src/toolkits/object_detection/object_detector.cpp [hunk 11]
```diff
@@ -353,23 +353,22 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
 void object_detector::import_from_custom_model(variant_map_type model_data,
                                                size_t version) {
   auto it = model_data.find("_model");
-  flex_dict model = variant_get_value<flex_dict>(it->second);
-  model_data.erase(it);
+  const flex_dict& model = variant_get_value<flex_dict>(it->second);
   auto it2 = model_data.find("_grid_shape");
+  if (it2 == model_data.end()) {
+    log_and_throw("The provided model must contain field '_grid_shape'!");
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: I don't think this should be an exception. If the grid shape is missing, for now we can assume the 13-by-13 grid from the original implementation

(It should, however, be an exception if "_model" is not found)

File: src/toolkits/object_detection/object_detector.cpp [hunk 12]
```diff
@@ -353,23 +353,22 @@ void object_detector::load_version(iarchive& iarc, size_t version) {
 void object_detector::import_from_custom_model(variant_map_type model_data,
                                                size_t version) {
   auto it = model_data.find("_model");
-  flex_dict model = variant_get_value<flex_dict>(it->second);
-  model_data.erase(it);
+  const flex_dict& model = variant_get_value<flex_dict>(it->second);
   auto it2 = model_data.find("_grid_shape");
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Since `it` and `it2` are used farther down in the function, could we give them more descriptive names?

File: src/toolkits/object_detection/object_detector.cpp [hunk 13]
```diff
@@ -898,6 +897,10 @@ std::unique_ptr<data_iterator> object_detector::create_iterator(
 
 std::unique_ptr<compute_context> object_detector::create_compute_context() const
 {
+  //add this line to prevent evaluation for python model from crash
+  if (state.find("use_tensorflow") == state.end()){
+    return compute_context::create();
```
Comment (nickjong) [inline src/toolkits/object_detection/object_detector.cpp]: Could you consult with Fareeha and Shreya? I don't think we want this logic here. Probably we can just remove "use_tensorflow" everywhere in the C++ code and just use `compute_context::create`
